# Unified Oracle 23ai + TPC-DS Helm Chart Configuration
# This chart deploys Oracle 23ai database and loads TPC-DS data using a single helm install

# Oracle Database Configuration
oracle:
  # Oracle Database requires single replica (cannot scale horizontally)
  replicaCount: 1

  image:
    repository: container-registry.oracle.com/database/free
    pullPolicy: IfNotPresent
    tag: "23.5.0.0"  # Using 23.5.0.0 for platform compatibility (latest has ORA-27350 issues)

  imagePullSecrets: []

  nameOverride: "oracle-db"
  fullnameOverride: "oracle-db"

  serviceAccount:
    create: true
    automount: true
    annotations: {}

  securityContextConstraint:
    create: true

  podAnnotations: {}
  podLabels: {}

  podSecurityContext:
    fsGroup: 54321

  securityContext:
    runAsUser: 54321
    runAsGroup: 54321
    runAsNonRoot: true

  service:
    type: ClusterIP
    port: 1521

  # Static environment configuration
  env:
    - name: ORACLE_CHARACTERSET
      value: "AL32UTF8"
    - name: ORACLE_EDITION
      value: "free"
    - name: ENABLE_ARCHIVELOG
      value: "true"

  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"

  # Enhanced health check configuration - tuned for Oracle 23ai startup
  probes:
    readiness:
      initialDelaySeconds: 180  # Allow time for Oracle initialization
      periodSeconds: 60        # Check every minute
      timeoutSeconds: 10
      failureThreshold: 20     # Allow up to 20 minutes total
    liveness:
      initialDelaySeconds: 300  # Start liveness checks after 5 minutes
      periodSeconds: 120       # Check every 2 minutes
      timeoutSeconds: 30

  autoscaling:
    enabled: false

  volumeClaimTemplates:
    - metadata:
        name: oracle-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

  volumeMounts:
    - mountPath: /opt/oracle/oradata
      name: oracle-data

  nodeSelector: {}
  affinity: {}
  tolerations: []

  # Connection configuration (shared across all user secrets)
  connection:
    host: oracle-db
    port: "1521"
    serviceName: "freepdb1"  # Pluggable database name
    sid: "FREE"  # Container database name

  # Database users with auto-generated passwords and schema management
  # Each user will get:
  # - Auto-generated secure password
  # - Kubernetes secret: oracle-db-user-<username>
  # - Access mode: rw (full access) or ro (read-only)
  #
  # Schema owners (username == schema) are created first
  # Alias users (username != schema) are created second with permissions to target schema
  #
  # SYSTEM user is the database administrator (required)
  users:
    - name: system
      schema: system
      mode: rw
      description: "Oracle SYSTEM administrator account"
    - name: sales
      schema: sales
      mode: rw
      description: "Sales schema owner for TPC-DS data"
    - name: sales_reader
      schema: sales
      mode: ro
      description: "Read-only alias for AI/MCP servers"

  # User management sidecar configuration (optional resource overrides)
  userManagement:
    resources: {}

# TPC-DS Data Loader Configuration
tpcds:
  # Enable TPC-DS data loading
  enabled: true

  # User configuration - which user from oracle.users should load TPC-DS data
  # This user must have mode: rw and will own the TPC-DS tables
  user: sales

  # TPC-DS Configuration
  scaleFactor: 1
  parallel: 2

  # Job configuration
  job:
    annotations: {}
    activeDeadlineSeconds: 3600  # 1 hour
    backoffLimit: 2

    # Resource configuration (optional overrides, defaults in template)
    resources: {}