{{- $root := . }}
{{- $models := include "llm-service.mergeModels" . | fromJson }}
{{- $usedDevices := dict }}
{{- range $key, $model := $models }}
  {{- if $model.enabled }}
    {{- $modelDevice := $model.device | default $root.Values.device }}
    {{- $_ := set $usedDevices $modelDevice true }}
  {{- end }}
{{- end }}
{{- range $device, $_ := $usedDevices }}
{{- $deviceConfig := index $root.Values.deviceConfigs $device }}
---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: {{ $root.Values.servingRuntime.name }}-{{ $device }}
  annotations:
    openshift.io/display-name: {{ $root.Values.servingRuntime.name }}-{{ $device }}
    {{- if $deviceConfig.recommendedAccelerators }}
    opendatahub.io/recommended-accelerators: '{{ $deviceConfig.recommendedAccelerators | toJson }}'
    {{- end }}
    opendatahub.io/apiProtocol: REST
    opendatahub.io/template-display-name: vLLM ServingRuntime for KServe ({{ $device | upper }})
    opendatahub.io/template-name: vllm-runtime-{{ $device }}
  labels:
    opendatahub.io/dashboard: "true"
    device: {{ $device }}
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    serving.knative.dev/progress-deadline: {{ $root.Values.servingRuntime.knativeTimeout }}
  containers:
  - command:
    - python3
    - -m
    - vllm.entrypoints.openai.api_server
    args:
    - --port
    - "8080"
    - --download-dir
    - /vllm/model
    {{-  with $root.Values.servingRuntime.env }}
    env:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq $device "gpu" }}
    image: {{ $root.Values.servingRuntime.gpuImage }}
    {{- else if eq $device "hpu" }}
    image: {{ $root.Values.servingRuntime.hpuImage }}
    {{- else }}
    image: {{ $root.Values.servingRuntime.cpuImage }}
    {{- end }}
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
    {{- with $root.Values.servingRuntime.volumeMounts }}
    volumeMounts:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
  {{- with $root.Values.servingRuntime.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
