builds:
  - name: mcp-weather
    containerfile: weather/Containerfile
    context: weather/src
  - name: oracle-sqlcl
    containerfile: oracle-sqlcl/Containerfile
    context: .  # Needs access to mcpproxy/ shared library
