apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-sqlcl-data
  namespace: appeng-3541-rhkp-production-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi