apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-sqlcl-data
  labels:
    app: mcp-servers
    component: oracle-sqlcl-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp3-csi