{{- $root := . }}
{{- $servers := include "mcp-servers.mergeMcpServers" . | fromJson }}
{{- range $key, $server := $servers }}
{{- if and $server.persistence $server.persistence.enabled }}
{{- $serverDict := dict "root" $root "key" $key "server" $server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $server.persistence.claimName }}
  labels:
    {{- include "mcp-servers.labels" $serverDict | nindent 4 }}
spec:
  accessModes:
    - {{ $server.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $server.persistence.size }}
  {{- if $server.persistence.storageClassName }}
  storageClassName: {{ $server.persistence.storageClassName }}
  {{- end }}
{{- end }}
{{- end }}