{{/*
SCC bindings for service accounts - iterating over mcp-servers for better maintainability
*/}}
{{- $root := . }}

{{/* ToolHive operator - always enabled */}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-toolhive-operator-anyuid
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: toolhive-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io

{{/* Dynamic SCC bindings for MCP servers */}}
{{- $servers := include "mcp-servers.mergeMcpServers" . | fromJson }}
{{- range $key, $server := $servers }}
{{- if $server.enabled }}
{{- $serverDict := dict "root" $root "key" $key "server" $server }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $root.Release.Namespace }}-{{ $key }}-proxy-runner-anyuid
  labels:
    {{- include "mcp-servers.labels" $serverDict | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ $key }}-proxy-runner
  namespace: {{ $root.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
