{{/*
Oracle 23ai StatefulSet with Enhanced Readiness Probes
*/}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "oracle-db.fullname" . }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: {{ .Values.oracle.replicaCount }}
  selector:
    matchLabels:
      {{- include "oracle-db.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  {{- with .Values.oracle.volumeClaimTemplates }}
  volumeClaimTemplates:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.oracle.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oracle-db.labels" . | nindent 8 }}
        app.kubernetes.io/component: database
        {{- with .Values.oracle.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.oracle.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oracle-db.serviceAccountName" . }}
      {{- with .Values.oracle.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: oracle-db
          {{- with .Values.oracle.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.oracle.image.repository }}:{{ .Values.oracle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.oracle.image.pullPolicy }}
          env:
            {{- toYaml .Values.oracle.env | nindent 12 }}
            # Secret-based environment variables
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: password
            - name: ORACLE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: username
            - name: ORACLE_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: serviceName
            - name: ORACLE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: port
          ports:
            - name: oracle
              containerPort: {{ .Values.oracle.service.port }}
              protocol: TCP
          {{/*
          Readiness probe: Test FREEPDB1 connectivity
          */}}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  # Test FREEPDB1 connectivity
                  echo "SELECT 'READY' FROM DUAL;" | sqlplus -s ${ORACLE_USER}/"${ORACLE_PWD}"@localhost:${ORACLE_PORT}/${ORACLE_SERVICE} 2>&1 | grep -q "READY"
            initialDelaySeconds: {{ .Values.oracle.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.oracle.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.oracle.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.oracle.probes.readiness.failureThreshold }}
          
          {{/* Liveness probe: Test database connectivity */}}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  echo "SELECT 'READY' FROM DUAL;" | sqlplus -s ${ORACLE_USER}/"${ORACLE_PWD}"@localhost:${ORACLE_PORT}/${ORACLE_SERVICE} | grep -q "READY"
            initialDelaySeconds: {{ .Values.oracle.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.oracle.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.oracle.probes.liveness.timeoutSeconds }}
          
          {{- with .Values.oracle.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.oracle.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        
        {{/* User Management Sidecar */}}
        {{- if .Values.oracle.users }}
        - name: user-manager
          image: "{{ .Values.oracle.image.repository }}:{{ .Values.oracle.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.oracle.image.pullPolicy }}
          command: ["/bin/bash", "/scripts/manage-users.sh"]
          env:
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: password
            - name: ORACLE_SERVICE
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: serviceName
            - name: ORACLE_HOST
              value: "localhost"
            - name: ORACLE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "oracle-db.fullname" . }}-user-system
                  key: port
            - name: SECRETS_DIR
              value: "/user-secrets"
          volumeMounts:
            - name: user-scripts
              mountPath: /scripts
              readOnly: true
            {{- range .Values.oracle.users }}
            - name: user-secret-{{ .name | replace "_" "-" }}
              mountPath: /user-secrets/{{ .name }}
              readOnly: true
            {{- end }}
          readinessProbe:
            exec:
              command:
                - test
                - -f
                - /tmp/users-ready
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 120
          resources:
            {{- if .Values.oracle.userManagement.resources }}
            {{- toYaml .Values.oracle.userManagement.resources | nindent 12 }}
            {{- else }}
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
            {{- end }}
        {{- end }}

      {{/* Volumes */}}
      volumes:
      {{- if .Values.oracle.users }}
        - name: user-scripts
          configMap:
            name: {{ include "oracle-db.fullname" . }}-user-scripts
            defaultMode: 0755
        {{- range .Values.oracle.users }}
        - name: user-secret-{{ .name | replace "_" "-" }}
          secret:
            secretName: {{ include "oracle-db.fullname" $ }}-user-{{ .name | replace "_" "-" }}
        {{- end }}
      {{- end }}

      {{- with .Values.oracle.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oracle.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.oracle.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}