apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-db.fullname" . }}
  labels:
    {{- include "oracle-db.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.oracle.service.type }}
  ports:
    - port: {{ .Values.oracle.service.port }}
      targetPort: oracle
      protocol: TCP
      name: oracle
  selector:
    {{- include "oracle-db.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database