apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-sqlcl-mcp.fullname" . }}
  labels:
    {{- include "oracle-sqlcl-mcp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "oracle-sqlcl-mcp.selectorLabels" . | nindent 4 }}