{{- if and .Values.customEndpoints.enabled .Values.customEndpoints.endpoints }}
{{- range $i, $ep := .Values.customEndpoints.endpoints }}
{{- if $ep.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: endpoint-api-key-{{ add $i 1 }}
  namespace: {{ $.Values.customEndpoints.namespace | default $.Release.Namespace }}
  labels:
    {{- include "playground.labels" $ | nindent 4 }}
type: Opaque
stringData:
  api_key: {{ $ep.apiKey }}
{{- end }}
{{- end }}
{{- end }}
