{{- if and .Values.vectorStores.enabled .Values.vectorStores.stores }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gen-ai-aa-vector-stores
  namespace: {{ .Values.vectorStores.namespace | default "redhat-ods-applications" }}
  labels:
    {{- include "playground.labels" . | nindent 4 }}
data:
  {{- range .Values.vectorStores.stores }}
  {{ .name }}: |
    {
      "url": {{ tpl .url $ | quote }}
      {{- if .vectorStoreName }},
      "vectorStoreName": {{ .vectorStoreName | quote }}
      {{- end }}
      {{- if .description }},
      "description": {{ .description | quote }}
      {{- end }}
    }
  {{- end }}
{{- end }}
