{{- if .Values.route.enabled }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }}
  labels:
    {{- include "ogx-ai.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  to:
    kind: Service
    name: {{ include "ogx-ai.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with .Values.route.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
