---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.secret.adminUser | b64enc | quote }}
  admin-password: {{ .Values.secret.adminPassword | b64enc | quote }}
---
{{- if .Values.secret.dbEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  db-url: {{ .Values.secret.dbUrl | b64enc | quote }}
  db-username: {{ .Values.secret.dbUsername | b64enc | quote }}
  db-password: {{ .Values.secret.dbPassword | b64enc | quote }}
{{- end }}
